export const USER_ACTION_TYPES = {
    // SET_CURRENT_USER: 'user/SET_CURRENT_USER',
    // CHECK_USER_SESSION: 'user/CHECK_USER_SESSION',

    REGISTER_USER_START: 'user/REGISTER_USER_START',
    REGISTER_USER_SUCCESS: 'user/REGISTER_USER_SUCCESS',
    REGISTER_USER_FAILED: 'user/REGISTER_USER_FAILED',

    LOGIN_USER_START: 'user/LOGIN_USER_START',
    LOGIN_USER_SUCCESS: 'user/LOGIN_USER_SUCCESS',
    LOGIN_USER_FAILED: 'user/LOGIN_USER_FAILED',

    LOGOUT_USER: 'user/LOGOUT_USER',

    SET_ACCESS_TOKEN: 'user/SET_ACCESS_TOKEN',
    SET_REFRESH_TOKEN: 'user/SET_REFRESH_TOKEN',

    SET_ACCESS_TOKEN_EXPIRY: 'user/SET_ACCESS_TOKEN_EXPIRY',

};
