export const USER_ACTION_TYPES = {
    // SET_CURRENT_USER: 'user/SET_CURRENT_USER',
    // CHECK_USER_SESSION: 'user/CHECK_USER_SESSION',

    EMAIL_SIGN_IN_START: 'user/EMAIL_SIGN_IN_START',
    EMAIL_SIGN_IN_SUCCESS: 'user/EMAIL_SIGN_IN_SUCCESS',
    EMAIL_SIGN_IN_FAILED: 'user/EMAIL_SIGN_IN_FAILED'
};
