export const USER_ACTION_TYPES = {
    // SET_CURRENT_USER: 'user/SET_CURRENT_USER',
    // CHECK_USER_SESSION: 'user/CHECK_USER_SESSION',

    REGISTER_USER_START: 'user/REGISTER_USER_START',
    REGISTER_USER_SUCCESS: 'user/REGISTER_USER_SUCCESS',
    REGISTER_USER_FAILED: 'user/REGISTER_USER_FAILED',

};
