PATCH http://localhost:3000/api/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIyLCJlbWFpbCI6Im1hcmtkb2VAZW1haWwuY29tIiwiaWF0IjoxNzQ4MDcxNzc5LCJleHAiOjE3NDgwNzUzNzksImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.IQTS0o5yuxHMOOczhPxhtd1aorxFQ3KlijI6Luk00XA

{
    "id": 23,
    "username": "johnathan",
    "email": "john2@email.com",
    "password": "Allizw3ll#",
    "userType": "BRAND",
    "dateOfBirth": "01-01-1998"
}



PATCH http://localhost:3000/api/users/assign-role
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIyLCJlbWFpbCI6ImpvaG5kb2VAZW1haWwuY29tIiwiaWF0IjoxNzQ4NzkxOTkzLCJleHAiOjE3NDg3OTU1OTMsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.H1WUI2Y07pURtHVhhh_O9PGzYGbS9lr-W7G9FE-UMGQ

{
    "googleId": "102818114883302847647",
    "userType": "BRAND"
}