PATCH http://localhost:3000/api/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIyLCJlbWFpbCI6ImpvaG5kb2VAZW1haWwuY29tIiwiaWF0IjoxNzQ5MTQ0NjM1LCJleHAiOjE3NDkxNDgyMzUsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.HH6TDSzdAOPPMJ_yHLM-YErKlWRqdhzat3W15sYwGeA

{
    "id": 22,
    "username": "johndoe",
    "email": "johndoe@email.com",
    "password": "Allizw3ll#",
    "user_type": "BRAND",
    "date_of_birth": "01-01-1998"
}



PATCH http://localhost:3000/api/users/assign-role
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIyLCJlbWFpbCI6ImpvaG5kb2VAZW1haWwuY29tIiwiaWF0IjoxNzQ4ODkwNDAwLCJleHAiOjE3NDg4OTQwMDAsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.Ice24uvvQDGSPbTyQaakAk7QtWr6Hsyh7zrLzYoPZ7k

{
    "password": "All2On3#",
    "user_type": "BRAND"
}