POST http://localhost:3000/api/auth/refresh-tokens
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIyLCJlbWFpbCI6Im1hcmtkb2VAZW1haWwuY29tIiwiaWF0IjoxNzQ4MDc3NTg3LCJleHAiOjE3NDgwODExODcsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.Ne81-hRCLY8JkIWKWNJQfWivGNq7Ys1JqTQzmX0HGaQ

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIyLCJpYXQiOjE3NDgwNzc1ODcsImV4cCI6MTc0ODE2Mzk4NywiYXVkIjoibG9jYWxob3N0OjMwMDAiLCJpc3MiOiJsb2NhbGhvc3Q6MzAwMCJ9.NUCmA9m7bMynGT5SKKRwICUj4rmznVV2dpSRlu8MTh4"
}