POST http://localhost:3000/api/auth/sign-in
Content-Type: application/json

{
    "identifier": "johndoe",
    "password": "All2On3#"
}



POST https://grvroy.com/nest/api/auth/sign-in
Content-Type: application/json


{
    "identifier": "johndoe",
    "password": "Kj#9mP$2nL"
}