export enum PaymentStatus {
    REQUIRES_PAYMENT_METHOD = 'REQUIRES_PAYMENT_METHOD',
    REQUIRES_CONFIRMATION = 'REQUIRES_CONFIRMATION',
    REQUIRES_ACTION = 'REQUIRES_ACTION',
    PROCESSING = 'PROCESSING',
    SUCCEEDED = 'SUCCEEDED',
    FAILED = 'FAILED',
    CANCELED = 'CANCELED',
}

