

export enum OfferingStatus{
    SPONSORED = 'SPONSORED',
    DRAFT = 'DRAFT',
    OFFERED = 'OFFERED',
    PENDING = 'PENDING',
    ACCEPTED = 'ACCEPTED',
    COMPLETED = 'COMPLETED',
    DISMISSED = 'DISMISSED',
    EXPIRED = 'EXPIRED'
}