

export enum TimeMode {
    TIMESPAN = 'TIMESPAN',
    START_TO_END = 'START_TO_END',
    PER_HOUR = 'PER_HOUR',
    EVENT_TRIGGER = 'EVENT_TRIGGER',
    FIXED_FREQUENCY = 'FIXED_FREQUENCY',
    SHOUTOUT = 'SHOUTOUT',
    AD_SEGMENT = 'AD_SEGMENT',
    PRODUCT_REVIEW = 'PRODUCT_REVIEW',
    VISUAL_OVERLAY = 'VISUAL_OVERLAY',
    SPONSORSHIP_INTRO_OUTRO = 'SPONSORSHIP_INTRO_OUTRO',
    CUSTOM = 'CUSTOM',
    INTRO_ONLY = 'INTRO_ONLY',
    OUTRO_ONLY = 'OUTRO_ONLY',
    FLASH_MENTION = 'FLASH_MENTION',
    PINNED_OVERLAY = 'PINNED_OVERLAY',
    HASTAG_ONLY = 'HASTAG_ONLY',
    SINGLE_APPEARANCE = 'SINGLE_APPEARANCE',
    HIGHLIGHT_MOMENT = 'HIGHLIGHT_MOMENT',
    PINNED_POST_TAG = 'PINNED_POST_TAG',
}