export const SocialPlatform = {
    TWITCH: "TWITCH",
    INSTAGRAM: "INSTAGRAM",
    X: "X",
    YOUTUBE: "YOUTUBE",
    TIKTOK: "TIKTOK",
    KICK: "KICK",
    FACEBOOK: "FACEBOOK",
    SNAPCHAT: "SNAPCHAT",
    PINTEREST: "PINTEREST",
    LINKEDIN: "LINKEDIN",
    THREADS: "THREADS",
    OTHER: "OTHER",
};