import { NativeSelect, TextInput } from "@mantine/core";
import { IconChevronDown, IconSearch } from "@tabler/icons-react";

export const searchFilterFieldsMapper = [
    {
        name: "search_input",
        className: "input-wrapper",
        variant: "secondaryGrey",
        label: "",
        placeholder: "type here",
        rightSection: <IconSearch size="1em" />,
        component: TextInput,
        componentType: "",
    },
    // {
    //     name: "teams",
    //     className: "input-wrapper",
    //     variant: "secondaryGrey",
    //     label: "",
    //     rightSection: <IconChevronDown size="1em" />,
    //     component: NativeSelect,
    //     componentType: "",
    //     options: ["type(orga,teams)", "Team Member", "Organization"],
    // },
    {
        name: "game",
        className: "input-wrapper",
        variant: "secondaryGrey",
        label: "",
        rightSection: <IconChevronDown size="1em" />,
        component: NativeSelect,
        componentType: "",
        options: ["game", "Valorant", "Fortnite", "League of Legends", "Apex Legends", "Call of Duty", "Overwatch", "Rainbow Six Siege", "CS:GO", "Dota 2", "PUBG", "Minecraft", "Roblox", "Fortnite", "League of Legends", "Apex Legends", "Call of Duty", "Overwatch", "Rainbow Six Siege", "CS:GO", "Dota 2", "PUBG", "Minecraft", "Roblox"],
    },
    {
        name: "country",
        className: "input-wrapper",
        variant: "secondaryGrey",
        label: "",
        rightSection: <IconChevronDown size="1em" />,
        component: NativeSelect,
        componentType: "",
        options: ["country", "United States", "Canada", "United Kingdom", "Australia", "New Zealand", "India", "Pakistan", "Afghanistan", "Bangladesh", "China", "Japan", "Korea", "Vietnam", "Thailand", "Malaysia", "Philippines", "Indonesia", "Singapore", "Hong Kong", "Macau", "Taiwan", "Mongolia", "Nepal", "Bhutan", "Sri Lanka", "Maldives", "Iran", "Iraq", "Syria", "Lebanon", "Jordan", "Palestine", "Israel", "Turkey", "Greece", "Bulgaria", "Romania", "Croatia", "Serbia", "Montenegro", "Albania", "Kosovo", "Macedonia", "Algeria", "Morocco", "Tunisia", "Libya", "Egypt", "Sudan", "Eritrea", "Ethiopia", "Somalia", "Kenya", "Tanzania", "Uganda", "Rwanda", "Burundi", "Central African Republic", "Chad", "Niger", "Nigeria", "Ghana", "Togo", "Benin", "Nigeria", "Ghana", "Togo", "Benin", "Nigeria", "Ghana", "Togo", "Benin", "Nigeria", "Ghana", "Togo", "Benin"],
    },
    {
        name: "gamein_partner",
        className: "input-wrapper",
        variant: "secondaryGrey",
        label: "",
        rightSection: <IconChevronDown size="1em" />,
        component: NativeSelect,
        componentType: "",
        options: ["gamein partner", "Yes", "No"],
    },
    {
        name: "followers",
        className: "input-wrapper",
        variant: "secondaryGrey",
        label: "",
        rightSection: <IconChevronDown size="1em" />,
        component: NativeSelect,
        componentType: "",
        options: ["followers", "1000", "2000", "3000", "4000", "5000", "6000", "7000", "8000", "9000", "10000"],
    },
    {
        name: "level",
        className: "input-wrapper",
        variant: "secondaryGrey",
        label: "",
        rightSection: <IconChevronDown size="1em" />,
        component: NativeSelect,
        componentType: "",
        options: ["level", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10"],
    },
    {
        name: "sortBy",
        className: "input-wrapper",
        variant: "secondaryGrey",
        label: "",
        rightSection: <IconChevronDown size="1em" />,
        component: NativeSelect,
        componentType: "",
        options: ["sort by", "Newest", "Oldest", "Most Followers", "Least Followers", "Most Level", "Least Level"],
    },
];